server:
  port: 10086
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/topicmanager?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 5000
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#fastdfs
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    height: 150
    width: 150
#  web-server-url: 192.168.1.3
  tracker-list: 192.168.1.4:22122
  pool:
    max-total: 200
    max-wait-millis: 25000
#ly:
#  upload:
#    allowTypes:
#      - image/jpeg
#      - image/jpg
#      - image/png
#      - image/bmp
